adminUser: admin
adminPassword: admin123  

persistence:
  enabled: true
  size: 2Gi

service:
  type: NodePort
  nodePort: 32000

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

rbac:
  create: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true
