alertmanager:
  enabled: true

server:
  persistentVolume:
    enabled: true
    size: 4Gi

  service:
    type: NodePort
    nodePort: 30090  

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  retention: "7d"

serviceAccounts:
  server:
    create: true
    name: prometheus-server-sa

rbac:
  create: true
